export const FETCH_AIRPORT_DATA_START = 'FETCH_AIRPORT_DATA_START';
export const FETCH_AIRPORT_DATA_SUCCESS = 'FETCH_AIRPORT_DATA_SUCCESS';
export const FETCH_AIRPORT_DATA_FAILED = 'FETCH_AIRPORT_DATA_FAILED';

export const FETCH_WEATHER_DATA_START = 'FETCH_WEATHER_DATA_START';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_WEATHER_DATA_FAILED = 'FETCH_WEATHER_DATA_FAILED';